import type { ErrorMap, ErrorMapEntry } from "../types.js";

const entries: ErrorMapEntry[] = [
  {
    code: 0,
    name: "InstructionUnpackError",
    explanation: "Failed to unpack instruction data",
    fix: "Check that the instruction data is correctly formatted",
    confidence: "low",
  },
  {
    code: 1,
    name: "InstructionPackError",
    explanation: "Failed to pack instruction data",
    fix: "Check that the instruction parameters are valid",
    confidence: "low",
  },
  {
    code: 2,
    name: "NotRentExempt",
    explanation: "Lamport balance below rent-exempt threshold",
    fix: "Fund the account with enough SOL to be rent-exempt",
    confidence: "high",
  },
  {
    code: 3,
    name: "AlreadyInitialized",
    explanation: "Account is already initialized",
    fix: "Use a new uninitialized account",
    confidence: "high",
  },
  {
    code: 4,
    name: "Uninitialized",
    explanation: "Account is not initialized",
    fix: "Initialize the account before using it",
    confidence: "high",
  },
  {
    code: 5,
    name: "InvalidMetadataKey",
    explanation: "Metadata key does not match expected PDA derived from mint",
    fix: "Ensure the metadata account is the correct PDA for the mint",
    confidence: "high",
  },
  {
    code: 6,
    name: "InvalidEditionKey",
    explanation: "Edition key does not match expected PDA",
    fix: "Ensure the edition account is the correct PDA",
    confidence: "high",
  },
  {
    code: 7,
    name: "UpdateAuthorityIncorrect",
    explanation: "Update authority does not match",
    fix: "Use the correct update authority for this metadata",
    confidence: "high",
  },
  {
    code: 8,
    name: "UpdateAuthorityIsNotSigner",
    explanation: "Update authority must sign the transaction",
    fix: "Ensure the update authority is a signer",
    confidence: "high",
  },
  {
    code: 9,
    name: "NotMintAuthority",
    explanation: "Signer is not the mint authority",
    fix: "Use the mint authority as the signer",
    confidence: "high",
  },
  {
    code: 10,
    name: "InvalidMintAuthority",
    explanation: "Mint authority does not match the authority on the mint",
    fix: "Provide the correct mint authority",
    confidence: "high",
  },
  {
    code: 11,
    name: "NameTooLong",
    explanation: "Metadata name exceeds maximum length",
    fix: "Shorten the name field",
    confidence: "high",
  },
  {
    code: 12,
    name: "SymbolTooLong",
    explanation: "Metadata symbol exceeds maximum length",
    fix: "Shorten the symbol field",
    confidence: "high",
  },
  {
    code: 13,
    name: "UriTooLong",
    explanation: "Metadata URI exceeds maximum length",
    fix: "Shorten the URI field",
    confidence: "high",
  },
  {
    code: 14,
    name: "UpdateAuthorityMustBeEqualToMetadataAuthorityAndSigner",
    explanation:
      "Update authority must match metadata authority and be a signer",
    fix: "Sign with the metadata update authority",
    confidence: "high",
  },
  {
    code: 15,
    name: "MintMismatch",
    explanation: "Mint does not match the mint on the metadata",
    fix: "Provide the correct mint account",
    confidence: "high",
  },
  {
    code: 16,
    name: "EditionsMustHaveExactlyOneToken",
    explanation: "Edition accounts must hold exactly one token",
    fix: "Ensure the edition has a supply of 1",
    confidence: "high",
  },
  {
    code: 17,
    name: "MaxEditionsMintedAlready",
    explanation: "Maximum number of editions have already been minted",
    fix: "No more prints can be minted from this master edition",
    confidence: "high",
  },
  {
    code: 18,
    name: "TokenMintToFailed",
    explanation: "Token mint operation failed",
    fix: "Check token account and mint permissions",
    confidence: "medium",
  },
  {
    code: 19,
    name: "MasterRecordMismatch",
    explanation: "Master edition record does not match",
    fix: "Provide the correct master edition account",
    confidence: "high",
  },
  {
    code: 20,
    name: "DestinationMintMismatch",
    explanation: "Destination account has the wrong mint",
    fix: "Use a token account with the correct mint",
    confidence: "high",
  },
  {
    code: 21,
    name: "EditionAlreadyMinted",
    explanation: "This edition has already been minted",
    fix: "Use a different edition number",
    confidence: "high",
  },
  {
    code: 22,
    name: "PrintingMintDecimalsShouldBeZero",
    explanation: "Printing mint must have zero decimals",
    fix: "Create the printing mint with 0 decimals",
    confidence: "medium",
  },
  {
    code: 23,
    name: "OneTimePrintingAuthorizationMintDecimalsShouldBeZero",
    explanation: "One-time printing auth mint must have zero decimals",
    fix: "Create the authorization mint with 0 decimals",
    confidence: "medium",
  },
  {
    code: 24,
    name: "EditionMintDecimalsShouldBeZero",
    explanation: "Edition mint must have zero decimals",
    fix: "Create the edition mint with 0 decimals",
    confidence: "medium",
  },
  {
    code: 25,
    name: "TokenBurnFailed",
    explanation: "Token burn operation failed",
    fix: "Ensure the token account has enough tokens and proper authority",
    confidence: "high",
  },
  {
    code: 26,
    name: "TokenAccountOneTimeAuthMintMismatch",
    explanation: "One-time auth mint does not match the token account",
    fix: "Use the correct token account for the authorization mint",
    confidence: "medium",
  },
  {
    code: 27,
    name: "DerivedKeyInvalid",
    explanation: "Derived PDA key is invalid",
    fix: "Verify the seeds used to derive the PDA",
    confidence: "high",
  },
  {
    code: 28,
    name: "PrintingMintMismatch",
    explanation: "Printing mint does not match the master edition",
    fix: "Use the correct printing mint for this master edition",
    confidence: "medium",
  },
  {
    code: 29,
    name: "OneTimePrintingAuthMintMismatch",
    explanation:
      "One-time printing auth mint does not match the master edition",
    fix: "Use the correct authorization mint",
    confidence: "medium",
  },
  {
    code: 30,
    name: "TokenAccountMintMismatch",
    explanation: "Token account mint does not match the printing mint",
    fix: "Use a token account with the printing mint",
    confidence: "medium",
  },
  {
    code: 31,
    name: "TokenAccountMintMismatchV2",
    explanation: "Token account mint does not match the master metadata mint",
    fix: "Use a token account with the correct mint",
    confidence: "medium",
  },
  {
    code: 32,
    name: "NotEnoughTokens",
    explanation: "Insufficient tokens to mint a limited edition",
    fix: "Acquire more tokens or reduce the edition quantity",
    confidence: "high",
  },
  {
    code: 33,
    name: "PrintingMintAuthorizationAccountMismatch",
    explanation:
      "Authorization token account mint does not match the printing mint",
    fix: "Use the correct authorization token account",
    confidence: "medium",
  },
  {
    code: 34,
    name: "AuthorizationTokenAccountOwnerMismatch",
    explanation:
      "Authorization token account owner differs from update authority",
    fix: "Use an authorization account owned by the update authority",
    confidence: "medium",
  },
  {
    code: 35,
    name: "Disabled",
    explanation: "This feature is currently disabled",
    fix: "Try an alternative instruction or wait for the feature to be re-enabled",
    confidence: "low",
  },
  {
    code: 36,
    name: "CreatorsTooLong",
    explanation: "Creators list exceeds maximum length",
    fix: "Reduce the number of creators",
    confidence: "high",
  },
  {
    code: 37,
    name: "CreatorsMustBeAtleastOne",
    explanation: "Creators array must have at least one entry if set",
    fix: "Add at least one creator or remove the creators field",
    confidence: "high",
  },
  {
    code: 38,
    name: "MustBeOneOfCreators",
    explanation: "Signer must be one of the listed creators",
    fix: "Sign with one of the creator addresses",
    confidence: "high",
  },
  {
    code: 39,
    name: "NoCreatorsPresentOnMetadata",
    explanation: "Metadata has no creators set",
    fix: "Add creators to the metadata first",
    confidence: "high",
  },
  {
    code: 40,
    name: "CreatorNotFound",
    explanation: "Creator address not found in metadata",
    fix: "Use a creator address that exists on the metadata",
    confidence: "high",
  },
  {
    code: 41,
    name: "InvalidBasisPoints",
    explanation: "Basis points value exceeds 10000",
    fix: "Use a basis points value between 0 and 10000",
    confidence: "high",
  },
  {
    code: 42,
    name: "PrimarySaleCanOnlyBeFlippedToTrue",
    explanation:
      "Primary sale flag can only be set to true and is immutable after",
    fix: "Set the primary sale flag to true only once",
    confidence: "medium",
  },
  {
    code: 43,
    name: "OwnerMismatch",
    explanation: "Account owner does not match expected value",
    fix: "Ensure the correct program owns the account",
    confidence: "high",
  },
  {
    code: 44,
    name: "NoBalanceInAccountForAuthorization",
    explanation: "Authorization token account has zero balance",
    fix: "Fund the authorization token account",
    confidence: "high",
  },
  {
    code: 45,
    name: "ShareTotalMustBe100",
    explanation: "Creator share percentages must sum to 100",
    fix: "Adjust creator shares to total exactly 100%",
    confidence: "high",
  },
  {
    code: 46,
    name: "ReservationExists",
    explanation: "Reservation list already exists for this edition",
    fix: "Use the existing reservation list",
    confidence: "medium",
  },
  {
    code: 47,
    name: "ReservationDoesNotExist",
    explanation: "Reservation list does not exist",
    fix: "Create the reservation list first",
    confidence: "medium",
  },
  {
    code: 48,
    name: "ReservationNotSet",
    explanation: "Reservation list exists but was never configured",
    fix: "Set reservations on the list before using it",
    confidence: "medium",
  },
  {
    code: 49,
    name: "ReservationAlreadyMade",
    explanation: "Reservation has already been set",
    fix: "Use a different reservation slot",
    confidence: "medium",
  },
  {
    code: 50,
    name: "BeyondMaxAddressSize",
    explanation: "Too many addresses provided for a single reservation",
    fix: "Reduce the number of addresses to within the limit",
    confidence: "medium",
  },
  {
    code: 51,
    name: "NumericalOverflowError",
    explanation: "Numerical overflow in calculation",
    fix: "Reduce the values involved in the operation",
    confidence: "low",
  },
  {
    code: 52,
    name: "ReservationBreachesMaximumSupply",
    explanation: "Reservation would exceed the master edition max supply",
    fix: "Reduce the reservation size to fit within supply limits",
    confidence: "medium",
  },
  {
    code: 53,
    name: "AddressNotInReservation",
    explanation: "Address is not in the reservation list",
    fix: "Use an address that is in the reservation",
    confidence: "medium",
  },
  {
    code: 54,
    name: "CannotVerifyAnotherCreator",
    explanation: "Cannot unilaterally verify another creator — they must sign",
    fix: "Have the creator sign the verification transaction",
    confidence: "high",
  },
  {
    code: 55,
    name: "CannotUnverifyAnotherCreator",
    explanation: "Cannot unilaterally unverify another creator",
    fix: "Have the creator sign the unverification transaction",
    confidence: "high",
  },
  {
    code: 56,
    name: "SpotMismatch",
    explanation:
      "Spots remaining should equal total spots on initial reservation",
    fix: "Set spots remaining equal to total spots",
    confidence: "low",
  },
  {
    code: 57,
    name: "IncorrectOwner",
    explanation: "Account has an incorrect owner",
    fix: "Use an account owned by the correct program",
    confidence: "high",
  },
  {
    code: 58,
    name: "PrintingWouldBreachMaximumSupply",
    explanation: "Printing more tokens would exceed max supply",
    fix: "Do not exceed the master edition max supply",
    confidence: "high",
  },
  {
    code: 59,
    name: "DataIsImmutable",
    explanation: "Metadata data is immutable and cannot be modified",
    fix: "Cannot modify — data was locked by the creator",
    confidence: "high",
  },
  {
    code: 60,
    name: "DuplicateCreatorAddress",
    explanation: "Duplicate creator addresses are not allowed",
    fix: "Remove duplicate creator addresses",
    confidence: "high",
  },
  {
    code: 61,
    name: "ReservationSpotsRemainingShouldMatchTotalSpotsAtStart",
    explanation: "Reservation spots must equal total spots at creation",
    fix: "Set remaining spots equal to total spots initially",
    confidence: "low",
  },
  {
    code: 62,
    name: "InvalidTokenProgram",
    explanation: "Invalid token program provided",
    fix: "Use the correct SPL Token program address",
    confidence: "high",
  },
  {
    code: 63,
    name: "DataTypeMismatch",
    explanation: "Data type does not match expected type",
    fix: "Provide the correct data type for this instruction",
    confidence: "medium",
  },
  {
    code: 64,
    name: "BeyondAlottedAddressSize",
    explanation: "Address exceeds the allotted reservation size",
    fix: "Use addresses within the reservation limit",
    confidence: "medium",
  },
  {
    code: 65,
    name: "ReservationNotComplete",
    explanation: "Reservation has only been partially allotted",
    fix: "Complete the reservation before using it",
    confidence: "medium",
  },
  {
    code: 66,
    name: "TriedToReplaceAnExistingReservation",
    explanation: "Cannot splice over an existing reservation",
    fix: "Use a new reservation slot",
    confidence: "medium",
  },
  {
    code: 67,
    name: "InvalidOperation",
    explanation: "Invalid operation attempted",
    fix: "Use a supported operation for this account state",
    confidence: "high",
  },
  {
    code: 68,
    name: "InvalidOwner",
    explanation: "Account has an invalid owner",
    fix: "Ensure the account is owned by the correct program",
    confidence: "high",
  },
  {
    code: 69,
    name: "PrintingMintSupplyMustBeZeroForConversion",
    explanation: "Printing mint supply must be zero before conversion",
    fix: "Burn all printing mint tokens before converting",
    confidence: "medium",
  },
  {
    code: 70,
    name: "OneTimeAuthMintSupplyMustBeZeroForConversion",
    explanation: "One-time auth mint supply must be zero before conversion",
    fix: "Burn all one-time auth tokens before converting",
    confidence: "medium",
  },
  {
    code: 71,
    name: "InvalidEditionIndex",
    explanation: "Edition index exceeds the edition mark PDA capacity",
    fix: "Use an edition number within the valid range",
    confidence: "medium",
  },
  {
    code: 72,
    name: "ReservationArrayShouldBeSizeOne",
    explanation: "Reservation array must be size one in the legacy system",
    fix: "Provide exactly one reservation entry",
    confidence: "low",
  },
  {
    code: 73,
    name: "IsMutableCanOnlyBeFlippedToFalse",
    explanation: "IsMutable can only be changed from true to false",
    fix: "Set isMutable to false to lock the metadata",
    confidence: "high",
  },
  {
    code: 74,
    name: "CollectionCannotBeVerifiedInThisInstruction",
    explanation: "Collection verification not supported in this instruction",
    fix: "Use the dedicated collection verification instruction",
    confidence: "medium",
  },
  {
    code: 75,
    name: "Removed",
    explanation: "Instruction has been deprecated and removed",
    fix: "Use the newer alternative instruction",
    confidence: "low",
  },
  {
    code: 76,
    name: "MustBeBurned",
    explanation: "Token must be burned for this operation",
    fix: "Burn the token before proceeding",
    confidence: "high",
  },
  {
    code: 77,
    name: "InvalidUseMethod",
    explanation: "Invalid use method specified",
    fix: "Use a valid use method (single, multiple, or burn)",
    confidence: "high",
  },
  {
    code: 78,
    name: "CannotChangeUseMethodAfterFirstUse",
    explanation: "Use method cannot be changed after the first use",
    fix: "Set the correct use method before the first use",
    confidence: "high",
  },
  {
    code: 79,
    name: "CannotChangeUsesAfterFirstUse",
    explanation:
      "Remaining or available uses cannot be changed after first use",
    fix: "Set the correct use count before the first use",
    confidence: "high",
  },
  {
    code: 80,
    name: "CollectionNotFound",
    explanation: "Collection not found on metadata",
    fix: "Verify the NFT belongs to a collection",
    confidence: "high",
  },
  {
    code: 81,
    name: "InvalidCollectionUpdateAuthority",
    explanation: "Collection update authority is invalid",
    fix: "Use the correct collection update authority",
    confidence: "high",
  },
  {
    code: 82,
    name: "CollectionMustBeAUniqueMasterEdition",
    explanation: "Collection parent must be a unique Master Edition v2",
    fix: "Use a Master Edition v2 as the collection parent",
    confidence: "high",
  },
  {
    code: 83,
    name: "UseAuthorityRecordAlreadyExists",
    explanation: "Use authority record already exists",
    fix: "Revoke the existing record before creating a new one",
    confidence: "high",
  },
  {
    code: 84,
    name: "UseAuthorityRecordAlreadyRevoked",
    explanation: "Use authority record is already revoked or empty",
    fix: "No action needed — record is already revoked",
    confidence: "high",
  },
  {
    code: 85,
    name: "Unusable",
    explanation: "Token has no uses configured",
    fix: "Configure uses on the token metadata first",
    confidence: "high",
  },
  {
    code: 86,
    name: "NotEnoughUses",
    explanation: "Not enough uses remaining on the token",
    fix: "The token has been fully used",
    confidence: "high",
  },
  {
    code: 87,
    name: "CollectionAuthorityRecordAlreadyExists",
    explanation: "Collection authority record already exists",
    fix: "Revoke the existing authority before approving a new one",
    confidence: "high",
  },
  {
    code: 88,
    name: "CollectionAuthorityDoesNotExist",
    explanation: "Collection authority record does not exist",
    fix: "Approve the collection authority first",
    confidence: "high",
  },
  {
    code: 89,
    name: "InvalidUseAuthorityRecord",
    explanation: "Use authority record is invalid",
    fix: "Provide a valid use authority record PDA",
    confidence: "medium",
  },
  {
    code: 90,
    name: "InvalidCollectionAuthorityRecord",
    explanation: "Collection authority record is invalid",
    fix: "Provide a valid collection authority record PDA",
    confidence: "medium",
  },
  {
    code: 91,
    name: "InvalidFreezeAuthority",
    explanation: "Metadata does not match the freeze authority on the mint",
    fix: "Set the correct freeze authority on the mint",
    confidence: "high",
  },
  {
    code: 92,
    name: "InvalidDelegate",
    explanation: "Not all tokens in the account are delegated to this user",
    fix: "Delegate the required tokens first",
    confidence: "high",
  },
  {
    code: 93,
    name: "CannotAdjustVerifiedCreator",
    explanation: "Cannot modify a verified creator entry",
    fix: "Unverify the creator before making changes",
    confidence: "high",
  },
  {
    code: 94,
    name: "CannotRemoveVerifiedCreator",
    explanation: "Verified creators cannot be removed",
    fix: "Unverify the creator before removing",
    confidence: "high",
  },
  {
    code: 95,
    name: "CannotWipeVerifiedCreators",
    explanation: "Cannot remove all verified creators at once",
    fix: "Unverify creators individually before removing",
    confidence: "high",
  },
  {
    code: 96,
    name: "NotAllowedToChangeSellerFeeBasisPoints",
    explanation: "Seller fee basis points cannot be changed",
    fix: "Set the correct fee at mint time",
    confidence: "medium",
  },
  {
    code: 97,
    name: "EditionOverrideCannotBeZero",
    explanation: "Edition override value cannot be zero",
    fix: "Provide a non-zero edition override",
    confidence: "medium",
  },
  {
    code: 98,
    name: "InvalidUser",
    explanation: "Invalid user account",
    fix: "Provide a valid user account",
    confidence: "high",
  },
  {
    code: 99,
    name: "RevokeCollectionAuthoritySignerIncorrect",
    explanation: "Signer for revoking collection authority is incorrect",
    fix: "Sign with the correct collection authority or update authority",
    confidence: "high",
  },
  {
    code: 100,
    name: "TokenCloseFailed",
    explanation: "Failed to close the token account",
    fix: "Ensure the token account has zero balance and correct authority",
    confidence: "medium",
  },
  {
    code: 101,
    name: "UnsizedCollection",
    explanation: "Cannot use this function on an unsized collection",
    fix: "Use the appropriate function for unsized collections",
    confidence: "medium",
  },
  {
    code: 102,
    name: "SizedCollection",
    explanation: "Cannot use this function on a sized collection",
    fix: "Use the appropriate function for sized collections",
    confidence: "medium",
  },
  {
    code: 103,
    name: "MissingCollectionMetadata",
    explanation: "Collection metadata account is missing",
    fix: "Provide the collection metadata account",
    confidence: "high",
  },
  {
    code: 104,
    name: "NotAMemberOfCollection",
    explanation: "NFT is not a member of the specified collection",
    fix: "Use an NFT that belongs to this collection",
    confidence: "high",
  },
  {
    code: 105,
    name: "NotVerifiedMemberOfCollection",
    explanation: "NFT is not a verified member of the specified collection",
    fix: "Verify the NFT in the collection first",
    confidence: "high",
  },
  {
    code: 106,
    name: "NotACollectionParent",
    explanation: "NFT is not the collection parent NFT",
    fix: "Use the collection parent NFT",
    confidence: "high",
  },
  {
    code: 107,
    name: "CouldNotDetermineTokenStandard",
    explanation: "Could not determine the token standard type",
    fix: "Ensure the token accounts are correctly configured",
    confidence: "medium",
  },
  {
    code: 108,
    name: "MissingEditionAccount",
    explanation: "Mint has an edition but no edition account was provided",
    fix: "Provide the edition account for this mint",
    confidence: "high",
  },
  {
    code: 109,
    name: "NotAMasterEdition",
    explanation: "Provided edition is not a master edition",
    fix: "Use a master edition account",
    confidence: "high",
  },
  {
    code: 110,
    name: "MasterEditionHasPrints",
    explanation: "Cannot modify master edition that has existing prints",
    fix: "Use a master edition with no minted prints",
    confidence: "high",
  },
  {
    code: 111,
    name: "BorshDeserializationError",
    explanation: "Borsh deserialization of account data failed",
    fix: "Ensure the account data is not corrupted",
    confidence: "low",
  },
  {
    code: 112,
    name: "CannotUpdateVerifiedCollection",
    explanation: "Cannot update a verified collection in this instruction",
    fix: "Unverify the collection first, then update",
    confidence: "high",
  },
  {
    code: 113,
    name: "CollectionMasterEditionAccountInvalid",
    explanation: "Edition account does not match the collection",
    fix: "Provide the correct edition account for the collection",
    confidence: "high",
  },
  {
    code: 114,
    name: "AlreadyVerified",
    explanation: "Item is already verified",
    fix: "No action needed — item is already verified",
    confidence: "high",
  },
  {
    code: 115,
    name: "AlreadyUnverified",
    explanation: "Item is already unverified",
    fix: "No action needed — item is already unverified",
    confidence: "high",
  },
  {
    code: 116,
    name: "NotAPrintEdition",
    explanation: "Edition is not a print edition",
    fix: "Use a print edition account",
    confidence: "high",
  },
  {
    code: 117,
    name: "InvalidMasterEdition",
    explanation: "Invalid master edition account",
    fix: "Provide a valid master edition account",
    confidence: "high",
  },
  {
    code: 118,
    name: "InvalidPrintEdition",
    explanation: "Invalid print edition account",
    fix: "Provide a valid print edition account",
    confidence: "high",
  },
  {
    code: 119,
    name: "InvalidEditionMarker",
    explanation: "Invalid edition marker account",
    fix: "Provide the correct edition marker PDA",
    confidence: "high",
  },
  {
    code: 120,
    name: "ReservationListDeprecated",
    explanation: "Reservation list feature is deprecated",
    fix: "Use the modern edition minting approach",
    confidence: "low",
  },
  {
    code: 121,
    name: "PrintEditionDoesNotMatchMasterEdition",
    explanation: "Print edition does not belong to this master edition",
    fix: "Use a print edition derived from this master edition",
    confidence: "high",
  },
  {
    code: 122,
    name: "EditionNumberGreaterThanMaxSupply",
    explanation: "Requested edition number exceeds max supply",
    fix: "Use an edition number within the max supply limit",
    confidence: "high",
  },
  {
    code: 123,
    name: "MustUnverify",
    explanation: "Must unverify before migrating collections",
    fix: "Unverify the collection item first",
    confidence: "high",
  },
  {
    code: 124,
    name: "InvalidEscrowBumpSeed",
    explanation: "Invalid bump seed for the escrow account",
    fix: "Use the correct bump seed derived from the PDA",
    confidence: "medium",
  },
  {
    code: 125,
    name: "MustBeEscrowAuthority",
    explanation: "Signer must be the escrow authority",
    fix: "Sign with the escrow authority",
    confidence: "high",
  },
  {
    code: 126,
    name: "InvalidSystemProgram",
    explanation: "Invalid system program provided",
    fix: "Use the official Solana System Program address",
    confidence: "high",
  },
  {
    code: 127,
    name: "MustBeNonFungible",
    explanation: "Operation requires a non-fungible token",
    fix: "Use an NFT with supply of 1 and no decimals",
    confidence: "high",
  },
  {
    code: 128,
    name: "InsufficientTokens",
    explanation: "Insufficient tokens for the transfer",
    fix: "Ensure the token account has enough tokens",
    confidence: "high",
  },
  {
    code: 129,
    name: "BorshSerializationError",
    explanation: "Borsh serialization of data failed",
    fix: "Check that all parameters are within valid ranges",
    confidence: "low",
  },
  {
    code: 130,
    name: "NoFreezeAuthoritySet",
    explanation: "Cannot create NFT without a freeze authority on the mint",
    fix: "Set a freeze authority on the mint first",
    confidence: "high",
  },
  {
    code: 131,
    name: "InvalidCollectionSizeChange",
    explanation: "Invalid collection size change",
    fix: "Provide a valid new collection size",
    confidence: "medium",
  },
  {
    code: 132,
    name: "InvalidBubblegumSigner",
    explanation: "Invalid bubblegum signer",
    fix: "Use the correct bubblegum signer account",
    confidence: "medium",
  },
  {
    code: 133,
    name: "EscrowParentHasDelegate",
    explanation: "Escrow parent account cannot have an active delegate",
    fix: "Revoke the delegate on the parent account first",
    confidence: "medium",
  },
  {
    code: 134,
    name: "MintIsNotSigner",
    explanation: "Mint account must be a signer for initialization",
    fix: "Sign the transaction with the mint keypair",
    confidence: "high",
  },
  {
    code: 135,
    name: "InvalidTokenStandard",
    explanation: "Invalid token standard specified",
    fix: "Use a supported token standard (NonFungible, FungibleAsset, Fungible, ProgrammableNonFungible)",
    confidence: "high",
  },
  {
    code: 136,
    name: "InvalidMintForTokenStandard",
    explanation:
      "Mint configuration does not match the specified token standard",
    fix: "Ensure mint settings (decimals, supply) match the token standard",
    confidence: "high",
  },
  {
    code: 137,
    name: "InvalidAuthorizationRules",
    explanation: "Invalid authorization rules account",
    fix: "Provide a valid authorization rules account",
    confidence: "medium",
  },
  {
    code: 138,
    name: "MissingAuthorizationRules",
    explanation: "Missing required authorization rules account",
    fix: "Provide the authorization rules account",
    confidence: "high",
  },
  {
    code: 139,
    name: "MissingProgrammableConfig",
    explanation: "Missing programmable configuration",
    fix: "Include the programmable config in the metadata",
    confidence: "medium",
  },
  {
    code: 140,
    name: "InvalidProgrammableConfig",
    explanation: "Invalid programmable configuration",
    fix: "Provide a valid programmable config with correct rule set",
    confidence: "medium",
  },
  {
    code: 141,
    name: "DelegateAlreadyExists",
    explanation: "Delegate already exists for this role",
    fix: "Revoke the existing delegate first",
    confidence: "high",
  },
  {
    code: 142,
    name: "DelegateNotFound",
    explanation: "Delegate not found for this operation",
    fix: "Approve a delegate for this role first",
    confidence: "high",
  },
  {
    code: 143,
    name: "MissingAccountInBuilder",
    explanation: "Required account not set in the instruction builder",
    fix: "Provide all required accounts to the instruction",
    confidence: "high",
  },
  {
    code: 144,
    name: "MissingArgumentInBuilder",
    explanation: "Required argument not set in the instruction builder",
    fix: "Provide all required arguments to the instruction",
    confidence: "high",
  },
  {
    code: 145,
    name: "FeatureNotSupported",
    explanation: "Feature not supported for this asset type",
    fix: "Use a compatible asset type for this feature",
    confidence: "medium",
  },
  {
    code: 146,
    name: "InvalidSystemWallet",
    explanation: "Invalid system wallet address",
    fix: "Provide a valid Solana wallet address",
    confidence: "high",
  },
  {
    code: 147,
    name: "OnlySaleDelegateCanTransfer",
    explanation: "Only the sale delegate can transfer this programmable asset",
    fix: "Use the sale delegate to authorize the transfer",
    confidence: "high",
  },
  {
    code: 148,
    name: "MissingTokenAccount",
    explanation: "Required token account is missing",
    fix: "Provide the token account for this operation",
    confidence: "high",
  },
  {
    code: 149,
    name: "MissingSplTokenProgram",
    explanation: "Missing SPL Token program account",
    fix: "Include the SPL Token program in the instruction",
    confidence: "high",
  },
  {
    code: 150,
    name: "MissingAuthorizationRulesProgram",
    explanation: "Missing authorization rules program account",
    fix: "Include the authorization rules program in the instruction",
    confidence: "high",
  },
  {
    code: 151,
    name: "InvalidDelegateRoleForTransfer",
    explanation: "Delegate role is not valid for this transfer type",
    fix: "Use the correct delegate role for the transfer",
    confidence: "high",
  },
  {
    code: 152,
    name: "InvalidTransferAuthority",
    explanation: "Invalid transfer authority",
    fix: "Provide the correct authority for the transfer",
    confidence: "high",
  },
  {
    code: 153,
    name: "InstructionNotSupported",
    explanation:
      "Instruction not supported for programmable non-fungible assets",
    fix: "Use the programmable-specific instruction variant",
    confidence: "high",
  },
  {
    code: 154,
    name: "KeyMismatch",
    explanation: "Public key does not match the expected value",
    fix: "Provide the correct account for this parameter",
    confidence: "high",
  },
  {
    code: 155,
    name: "LockedToken",
    explanation: "Token is locked and cannot be transferred",
    fix: "Unlock the token before transferring",
    confidence: "high",
  },
  {
    code: 156,
    name: "UnlockedToken",
    explanation: "Token is already unlocked",
    fix: "No action needed — token is already unlocked",
    confidence: "high",
  },
  {
    code: 157,
    name: "MissingDelegateRole",
    explanation: "Required delegate role is not set",
    fix: "Approve the required delegate role first",
    confidence: "high",
  },
  {
    code: 158,
    name: "InvalidAuthorityType",
    explanation: "Invalid authority type specified",
    fix: "Use a valid authority type for this operation",
    confidence: "high",
  },
  {
    code: 159,
    name: "MissingTokenRecord",
    explanation: "Missing token record account",
    fix: "Provide the token record PDA for this asset",
    confidence: "high",
  },
  {
    code: 160,
    name: "MintSupplyMustBeZero",
    explanation: "Mint supply must be zero for programmable assets",
    fix: "Use a fresh mint with zero supply",
    confidence: "high",
  },
  {
    code: 161,
    name: "DataIsEmptyOrZeroed",
    explanation: "Account data is empty or zeroed",
    fix: "Use an account that has been properly initialized",
    confidence: "high",
  },
  {
    code: 162,
    name: "MissingTokenOwnerAccount",
    explanation: "Missing token owner account",
    fix: "Provide the token owner account",
    confidence: "high",
  },
  {
    code: 163,
    name: "InvalidMasterEditionAccountLength",
    explanation: "Master edition account has an invalid data length",
    fix: "Use a properly created master edition account",
    confidence: "low",
  },
  {
    code: 164,
    name: "IncorrectTokenState",
    explanation: "Token is in an incorrect state for this operation",
    fix: "Ensure the token is in the correct state (locked/unlocked)",
    confidence: "high",
  },
  {
    code: 165,
    name: "InvalidDelegateRole",
    explanation: "Invalid delegate role specified",
    fix: "Use a valid delegate role (Sale, Transfer, Utility, Staking, etc.)",
    confidence: "high",
  },
  {
    code: 166,
    name: "MissingPrintSupply",
    explanation: "Print supply is required for non-fungible tokens",
    fix: "Set the print supply to zero or one",
    confidence: "medium",
  },
  {
    code: 167,
    name: "MissingMasterEditionAccount",
    explanation: "Missing master edition account",
    fix: "Provide the master edition account",
    confidence: "high",
  },
  {
    code: 168,
    name: "AmountMustBeGreaterThanZero",
    explanation: "Amount must be greater than zero",
    fix: "Provide a positive amount",
    confidence: "high",
  },
  {
    code: 169,
    name: "InvalidDelegateArgs",
    explanation: "Invalid delegate arguments provided",
    fix: "Provide the correct delegate arguments for the delegate role",
    confidence: "medium",
  },
  {
    code: 170,
    name: "MissingLockedTransferAddress",
    explanation: "Missing address for locked transfer",
    fix: "Provide the destination address for the locked transfer",
    confidence: "medium",
  },
  {
    code: 171,
    name: "InvalidLockedTransferAddress",
    explanation: "Invalid destination address for locked transfer",
    fix: "Provide a valid destination for the locked transfer",
    confidence: "medium",
  },
  {
    code: 172,
    name: "DataIncrementLimitExceeded",
    explanation: "Account reallocation increase limit exceeded",
    fix: "Reduce the data size increase",
    confidence: "medium",
  },
  {
    code: 173,
    name: "CannotUpdateAssetWithDelegate",
    explanation: "Cannot update asset while a delegate is active",
    fix: "Revoke the delegate before updating the asset",
    confidence: "high",
  },
  {
    code: 174,
    name: "InvalidAmount",
    explanation: "Invalid token amount for this operation or token standard",
    fix: "Use the correct amount for the token type",
    confidence: "high",
  },
  {
    code: 175,
    name: "MissingMasterEditionMintAccount",
    explanation: "Missing master edition mint account",
    fix: "Provide the mint account of the master edition",
    confidence: "high",
  },
  {
    code: 176,
    name: "MissingMasterEditionTokenAccount",
    explanation: "Missing master edition token account",
    fix: "Provide the token account holding the master edition",
    confidence: "high",
  },
  {
    code: 177,
    name: "MissingEditionMarkerAccount",
    explanation: "Missing edition marker account",
    fix: "Provide the edition marker PDA",
    confidence: "high",
  },
  {
    code: 178,
    name: "CannotBurnWithDelegate",
    explanation: "Cannot burn while a persistent delegate is set",
    fix: "Revoke the delegate before burning",
    confidence: "high",
  },
  {
    code: 179,
    name: "MissingEdition",
    explanation: "Missing edition account",
    fix: "Provide the edition account",
    confidence: "high",
  },
  {
    code: 180,
    name: "InvalidAssociatedTokenAccountProgram",
    explanation: "Invalid associated token account program",
    fix: "Use the official SPL Associated Token Program",
    confidence: "high",
  },
  {
    code: 181,
    name: "InvalidInstructionsSysvar",
    explanation: "Invalid instructions sysvar",
    fix: "Use the correct instructions sysvar address",
    confidence: "low",
  },
  {
    code: 182,
    name: "InvalidParentAccounts",
    explanation: "Invalid or unneeded parent accounts provided",
    fix: "Provide the correct parent accounts for this instruction",
    confidence: "medium",
  },
  {
    code: 183,
    name: "InvalidUpdateArgs",
    explanation: "Authority cannot apply all the requested update args",
    fix: "Use update args that the current authority is allowed to apply",
    confidence: "medium",
  },
  {
    code: 184,
    name: "InsufficientTokenBalance",
    explanation: "Token account has insufficient tokens",
    fix: "Ensure the token account has enough tokens",
    confidence: "high",
  },
  {
    code: 185,
    name: "MissingCollectionMint",
    explanation: "Missing collection mint account",
    fix: "Provide the collection mint account",
    confidence: "high",
  },
  {
    code: 186,
    name: "MissingCollectionMasterEdition",
    explanation: "Missing collection master edition account",
    fix: "Provide the collection master edition account",
    confidence: "high",
  },
  {
    code: 187,
    name: "InvalidTokenRecord",
    explanation: "Invalid token record account",
    fix: "Provide the correct token record PDA",
    confidence: "high",
  },
  {
    code: 188,
    name: "InvalidCloseAuthority",
    explanation:
      "Close authority must be revoked by the utility delegate first",
    fix: "Revoke close authority via the utility delegate",
    confidence: "medium",
  },
  {
    code: 189,
    name: "InvalidInstruction",
    explanation: "Invalid or removed instruction",
    fix: "Use a valid supported instruction",
    confidence: "high",
  },
  {
    code: 190,
    name: "MissingDelegateRecord",
    explanation: "Missing delegate record account",
    fix: "Provide the delegate record PDA",
    confidence: "high",
  },
  {
    code: 191,
    name: "InvalidFeeAccount",
    explanation: "Invalid fee account",
    fix: "Provide a valid fee account",
    confidence: "medium",
  },
  {
    code: 192,
    name: "InvalidMetadataFlags",
    explanation: "Invalid metadata flags set",
    fix: "Use valid flag values for metadata configuration",
    confidence: "medium",
  },
  {
    code: 193,
    name: "CannotChangeUpdateAuthorityWithDelegate",
    explanation: "Cannot change update authority while a delegate is active",
    fix: "Revoke the delegate before changing update authority",
    confidence: "high",
  },
  {
    code: 194,
    name: "InvalidMintExtensionType",
    explanation: "Invalid mint extension type for this operation",
    fix: "Use a compatible mint extension type",
    confidence: "medium",
  },
  {
    code: 195,
    name: "InvalidMintCloseAuthority",
    explanation: "Invalid mint close authority",
    fix: "Set the correct close authority on the mint",
    confidence: "medium",
  },
  {
    code: 196,
    name: "InvalidMetadataPointer",
    explanation: "Invalid metadata pointer extension",
    fix: "Configure the metadata pointer correctly on the mint",
    confidence: "medium",
  },
  {
    code: 197,
    name: "InvalidTokenExtensionType",
    explanation: "Invalid token extension type",
    fix: "Use a supported token extension type",
    confidence: "medium",
  },
  {
    code: 198,
    name: "MissingImmutableOwnerExtension",
    explanation: "Missing required immutable owner extension",
    fix: "Create the token account with immutable owner extension",
    confidence: "medium",
  },
  {
    code: 199,
    name: "ExpectedUninitializedAccount",
    explanation: "Expected account to be uninitialized",
    fix: "Use a fresh account that has not been initialized",
    confidence: "high",
  },
  {
    code: 200,
    name: "InvalidEditionAccountLength",
    explanation: "Edition account has an invalid data length",
    fix: "Use a properly created edition account",
    confidence: "low",
  },
  {
    code: 201,
    name: "AccountAlreadyResized",
    explanation: "Account has already been resized",
    fix: "No additional resizing is needed",
    confidence: "high",
  },
  {
    code: 202,
    name: "ConditionsForClosingNotMet",
    explanation: "Conditions for closing the account are not met",
    fix: "Ensure all prerequisites for closing are satisfied",
    confidence: "high",
  },
];

export const metaplexErrorMap: ErrorMap = new Map(
  entries.map((e) => [e.code, e]),
);
